services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    entrypoint: "uv run"
    command: "uvicorn travel_map.app:app --host 0.0.0.0 --port 8000 --reload"

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
