services:
  app:
    build:
      context: ..
      dockerfile: ./deployment/Dockerfile
    ports:
      - "8000:8000"
    entrypoint: "uv run --no-sync"
    command: "uv run --no-sync uvicorn travel_map.app:app --host 0.0.0.0 --port 8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file: .env

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
