services:
  app:
    build:
      context: ..
      dockerfile: ./deployment/Dockerfile
    ports:
      - "8000:8000"
    entrypoint: "uv run --no-sync"
    command: "uv run --no-sync uvicorn travel_map.app:app --host 0.0.0.0 --port 8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file: ../.env

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning", "--appendonly", "yes"]

  db:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: supersecret
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis-data:
  pgdata:
