"""add password

Revision ID: 1339b3d8075f
Revises: 345324390cba
Create Date: 2025-09-24 16:21:09.723813

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1339b3d8075f"
down_revision: Union[str, Sequence[str], None] = "345324390cba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "usermodel", sa.Column("hashed_password", sa.String(length=255), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usermodel", "hashed_password")
    # ### end Alembic commands ###
