"""make email primary key

Revision ID: 345324390cba
Revises: 6d7f0917ca7c
Create Date: 2025-09-20 17:58:08.727481

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "345324390cba"
down_revision: Union[str, Sequence[str], None] = "6d7f0917ca7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_user_email", "usermodel", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_email", "usermodel", type_="unique")
    # ### end Alembic commands ###
