"""not mark email as primary

Revision ID: e2703a29f660
Revises: 1339b3d8075f
Create Date: 2025-09-24 19:07:27.699474

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "e2703a29f660"
down_revision: Union[str, Sequence[str], None] = "1339b3d8075f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
