name: Deploy to VPS

on:
  push:
    branches:
      - test-ga

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: mikrus

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Copy files to VPS
      run: |
        rsync -e "ssh -p 10183" -avz --delete ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/root/p/myapp/
